spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    hikari.maxium-pool-size: 4
    url: jdbc:postgresql://ec2-54-163-140-5.compute-1.amazonaws.com/de3cestlqkekp0
    username: u7bjqnltofpp1p
    password: p240170e441a1aa72fee6bba192898a83e9c30edf1f7aeb94329e15e34bc3dc2c
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  token.expired-time-ms: 2592000000