spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: uno

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis.url: redis://localhost:6379

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${DATABASE_URL}
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
  # TODO: 헤로쿠 환경에서 Redis 사용 안 함
  data.redis.repositories.enabled: false
